Feature branch merge
euqueme/enumerable-methods pull request #2
Opened 2019-10-30 02:10 UTC by euqueme

Requesting to merge on my development branch,

I disabled the cops: Metrics/CyclomaticComplexity, Metrics/MethodLength and Metrics/PerceivedComplexity
on my_all? my_any? my_none? and my_count? methods because they take arguments and are longer than 10 lines. 

Thank you in advance for your kind review.

2019-10-31 09:01 UTC, bolah2009 requested changes
## Hey @euqueme   :wave: 

### This is an awesome effort :clap: :smile: 

Let's make changes to these methods (check comments for more details)
- `my_each?`
- `my_each_with_index?`
- `my_select?`
- `my_map?`
- `my_all?`
- `my_any?`
- `my_none?`
- `my_inject`

A reminder from pathwright:

> Take a look at Ruby docs about Enumerable class https://ruby-doc.org/core-2.6.5/Enumerable.html

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-10-31 09:01 UTC, bolah2009 commented on main.rb
> +  end
`my_each` should return an enumerator when no block is given.

We could add a line that returns `to_enum` when no block is given.

> If no block is given, an enumerator is returned instead.

This applies to `my_each_with_index`, `my_select` and `my_map`.

2019-10-31 09:01 UTC, bolah2009 commented on main.rb
> +  end
This line will result in an error when we pass an integer or string. For example: `[1,2,3].my_all?(2)` gives a `TypeError`

```ruby
          output = element.is_a?(arg) unless arg.is_a?(Regexp)
          output = element.match?(arg) if arg.is_a?(Regexp)
```
Let's handle cases when `arg` is not a class.
### Find more details about [`all?` here](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F)

2019-10-31 09:01 UTC, bolah2009 commented on main.rb
> +  end
Please see the comment on `my_all?`

### Find more details about [`any?` here](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F)

2019-10-31 09:01 UTC, bolah2009 commented on main.rb
> +  end
Please, see comment on `my_all?`

### Find more details about [`none?` here](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F)

[OPTIONAL]

I think if we could get the block from `my_none?` to `my_any?` we should only need something like `!my_any?` for `my_none?` to work fine. For example:

```ruby
  def my_none?(arg = nil, &block)
    !my_any?(arg = nil,&block)
  end
```

To make this work we have to use `block.call(element)` instead of `yield(element)` in `my_any?`

2019-10-31 09:01 UTC, bolah2009 commented on main.rb
> +  end
Let's handle cases where a `block` is not given and a `Symbol` or operator is passed instead. 

For example: `[1,2,3].my_inject(:+)` should equal `[1,2,3].inject(:+)`

HINT: Investigate the [`send`](https://ruby-doc.org/core-2.6.3/Object.html#method-i-send) method. Since `2.send(:+, 2) == 4`

2019-11-01 17:20 UTC, euqueme commented on main.rb
> +  end
Solved! thank you very much for your reviews and suggestion I challenged myself and learned a lot.

Keep up the good work!!

2019-11-01 17:27 UTC, bolah2009 commented on main.rb
> +  end
Glad to hear 😀

2019-11-01 17:36 UTC, euqueme commented
I fix all the changes requested by @bolah2009 

So right now:
- my_each, my_each_with_index, my_map and my_select return an enumerable if no block is given
- my_any validates objects 
- my_none is the negation of my_any
- my_inject takes symbols  or strings as parameters to operate the enumerable

Thank you in advance for your kind review.

2019-11-02 13:13 UTC, samgaco requested changes
Hi @euqueme :high_brightness: 

5 points to correct indicated in the comments below, please work on these changes and submit back for another code review once you are done.

Good spirit :muscle: 

---------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-11-02 13:13 UTC, samgaco commented on main.rb
> +      self
here `self` would be returning the array the method it's evaluating, for example:

```
irb(main):116:0> [1,2,3].my_each
=> [1, 2, 3]
```

but we want

```
irb(main):117:0> [1,2,3].each
=> #<Enumerator: [1, 2, 3]:each>
```

therefore, maybe we should transform self into a enumerator, something like `self.to_enum`  to get:

```
irb(main):118:0> [1,2,3].to_enum
=> #<Enumerator: [1, 2, 3]:each>
```

2019-11-02 13:13 UTC, samgaco commented on main.rb
> +      return self
returning self again, it should be an enumerator what is returned for this method

```
irb(main):119:0> [1,2].map
=> #<Enumerator: [1, 2]:map>
```

2019-11-02 13:13 UTC, samgaco commented on main.rb
> +      self
should return an enumerator

2019-11-02 13:13 UTC, samgaco commented on main.rb
> +      self
should be returning an enumerator

2019-11-02 13:13 UTC, samgaco commented on main.rb
> +      if output
you've got a gap in this method, check it out here compared as the original:

```
irb(main):123:0> ["abc",  "abc"].all?("abc")
=> true
irb(main):124:0> ["abc",  "abc"].my_all?("abc")
=> true
irb(main):125:0> ["abc",  1].all?("abc")
=> false
irb(main):126:0> ["abc",  1].my_all?("abc")
=> true
```

2019-11-04 04:39 UTC, euqueme commented
I fix all the changes requested by @samgaco :

- All self returns were changed to to_enum 
- Fix gap in my_all for "elsif arg" so output can be set to either true or false

The code passes all cops.

Thank you in advance for your kind review.

2019-11-04 15:33 UTC, AdnanAfsari approved these changes
**Status: Approved**

Looks good now, its a 👍 from me.

Happy Coding
Adnan Afsari

2019-11-05 23:19 UTC, merged